export { FeaturedWorkSection, FeaturedWork } from './FeaturedWork'
export { FeaturedIntro } from './FeaturedIntro'
export { FeaturedBackground } from './FeaturedBackground'
export { ProjectShowcase } from './ProjectShowcase'
export { ProjectImage } from './ProjectImage'
export { CaseStudy } from './CaseStudy'
export { TechStack } from './TechStack'
export { MetricGrid } from './MetricGrid'
export { ProjectActions } from './ProjectActions'
export { FEATURED_PROJECTS, FEATURED_WORK } from './constants'
